### ISSUE TITLE
Potential Form of Some Intelisense 

### ISSUE THREAD

**Issue by MeDerpWasTaken** [game-creators-area/Advisor#4]
[This repository](https://github.com/Joe4422/SandboxTools)  contains some of the S&Box API (it hasn't been updated for a while so it's probably outdated), so this could be used to reduce the amount of errors and get some Intelisense, of course not all of it needs to be used but some of it being used could help a bit

**Comment by Erlite** [comment]
Yeah I was made aware of it a while ago, the reason I decided not to use it is that s&box's API changes daily, so instead of wasting time implementing things without being able to test them, I might as well keep going on in a game agnostic manner.

I do have some stubs, notably the player class, but that's about it.

**Comment by MeDerpWasTaken** [comment]
Makes sense, in my opinion just taking a couple of files (ex. Player) could help but it's your decision
